### ISSUE TITLE
Create package for conda-forge

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-sphinx-theme#6]
### What is the idea?

Currently, this theme is available on `pip`. We would also like to make it available as a conda-forge package so that projects can just conda for managing their dependencies if they want to.

**Comment by kathatherine** [comment]
PR to add to conda-forge is here: https://github.com/conda-forge/staged-recipes/pull/24523

**Comment by kathatherine** [comment]
Package is merged to conda-forge and @travishathaway and @kathatherine are listed as maintainers and members of conda-forge, so good to go. 🚀
